### ISSUE TITLE
this.customStyle not changing --paper-tabs-selection-bar-color

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-tabs#111]
I can not get the paper tabs selection bar to change color to change when I invoke changeColor(). Am I doing something wrong?

```
{
  "name": "paper-tabs",
  "version": "1.2.4",
```

###### Polymer 1.2 

```html
<dom-module id="paper-tabs-custom">
  <style>
        paper-tabs {
      --paper-tabs-selection-bar-color: white;
    }

    paper-tab {
      --paper-tab-content-unselected: {
        opacity: 1.0;
      }
    }

    paper-tab {
      font-weight: 700;
    }

    paper-tab[name="portfolio"] {
      width: 161px;
    }
  </style>
  <template>
    <paper-tabs noink="true" 
      attr-for-selected="name"
      selected="{{setSelected}}">
      <paper-tab data-name="home" data-px="240" name="home" on-tap="jumpToPage">
        HOME
      </paper-tab>
      <paper-tab data-name="portfolio" data-px="180" name="portfolio" on-tap="jumpToPage">
        PORTFOLIO
     </paper-tabs>
  </template>
  <script>
    Polymer({
      is: "paper-tabs-custom",
      changeColor: function() {
        this.customStyle['--paper-tabs-selection-bar-color'] = 'black';
        this.updateStyles();
      }
    });
  </script>
</dom-module>
```

**Comment by bicknellr** [comment]
The issue you're running into is that the CSS rule with selector `paper-tabs` overrides the value of `--paper-tabs-selection-bar-color` that you're setting on `customStyle` of the host. Values from any CSS rules that match an element will have higher precedence than any values that cascade to those elements; change `customStyle` of the `paper-tabs` directly and it should work.

(Alternatively, moving the `--paper-tabs-selection-bar-color` to a `:host` rule would work, but would be fixing this by making your baseline CSS less specific rather than making your update more specific. Arguably more sloppy, but it demonstrates what's going on.)
