### ISSUE TITLE
[2.0-preview] Tabs aren't inline and styled properly

### ISSUE THREAD

**Issue by tedsenft** [PolymerElements/paper-tabs#196]
### Expected outcome
Paper tabs are inlined and styled to fit as a block, like the original version.

### Actual outcome
Tabs are block-level and have no styling.

### Live Demo

http://codepen.io/nanobird_/pen/VPjBGR?editors=1011

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
Unfortunately, you have to make sure *all* of your dependencies are included and pointing at the correct branch in the polygit base url if you want anything besides master. I added the direct dependencies of paper-tabs in this demo: http://codepen.io/anon/pen/qRvEvv and it seems to be 'working'. However, I didn't go hunt down the transitive dependencies, so I'm kind of surprised it managed to work anyways. :) I wouldn't trust me if I were you; feel free to check out the paper-tabs repo on the 2.0-preview branch and run the demo locally so that bower will grab all the correct dependencies for you.

**Comment by tedsenft** [comment]
Still messing around locally. Whether it's in a 2.0 element or not, it does not matter.

![image](https://cloud.githubusercontent.com/assets/8529636/23009832/24cf0bd4-f3e6-11e6-9600-b5e92e8d44aa.png)

Even tried removing the tabs completely and re-downloading all the things. Also tried moving the element around in and out of the main document, elements, and with dynamic imports with polymer.importHref.

Nothing.

**Comment by bicknellr** [comment]
The demo I linked to above stopped working and I think it's because shadycss isn't one of the default repos for polygit (?) and needed to be added explicitly: https://codepen.io/anon/pen/webKMj?editors=1000#0 . Are you seeing any 404s for files in the shadycss repo?
