### ISSUE TITLE
Can't install older versions anymore

### ISSUE THREAD

**Issue by fiducioso-dan** [PolymerElements/paper-tabs#240]
### Description
Can't install version 1.8.0 anymore. I have been using bower but also npm fails.

### Expected outcome

`npm install @polymer/paper-tabs@^1.8.0` succeeds.
### Actual outcome

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @polymer/paper-tabs@^1.8.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by fiducioso-dan** [comment]
Workaround for anyone else running in to this issue:

```
bower install --save paper-tabs=git://github.com/PolymerElements/paper-tabs#v1.8.0
```

Well that's how to fix it in Bower anyway. I know npm has something similar.

**Comment by bicknellr** [comment]
Hi! We didn't officially support installation over NPM until v3.0.0. There were lots of false starts (which you can browse on [NPM's paper-tabs versions page](https://www.npmjs.com/package/@polymer/paper-tabs?activeTab=versions)) but they're all prerelease versions (i.e. <1.0.0 or have a prerelease suffix). Though, `bower install PolymerElements/paper-tabs#^1.8.0` still seems to work for me. Let me know if you run into this situation with any non-prerelease versions though!

Also, if you're using Polymer 1 or 2, please make sure you've read this [blog post about confirming that you've set up the polyfills correctly](https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade) because [Chrome is deprecating the old version of the specs (v0)](https://developers.google.com/web/updates/2019/12/chrome-80-deps-rems#web_components_v0_removed) next month!
